name: Bug report
description: Report a reproducible problem in PaperPilot
title: "[Bug] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please include exact commands and logs so we can reproduce quickly.

  - type: textarea
    id: summary
    attributes:
      label: What happened?
      description: Describe the actual behavior and what you expected.
      placeholder: When I run `python scripts/...`, it fails with ...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Provide exact commands and inputs.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs/output
      description: Paste error messages or attach snippets from logs.
      render: shell

  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: e.g. 3.11.9
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS
      placeholder: e.g. macOS 15.2 / Ubuntu 24.04
    validations:
      required: true
